/// Automated CRM campaign actions sent to at-risk customers
table CampaignActions

	column CustomerKey
		dataType: int64
		sourceColumn: CustomerKey

	column FirstName
		dataType: string
		sourceColumn: FirstName

	column LastName
		dataType: string
		sourceColumn: LastName

	column Occupation
		dataType: string
		sourceColumn: Occupation

	column Segment
		dataType: string
		sourceColumn: Segment

	column RiskBand
		dataType: string
		sourceColumn: RiskBand

	column ChurnRiskScore
		dataType: double
		summarizeBy: sum
		sourceColumn: ChurnRiskScore

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalSpend
		dataType: double
		summarizeBy: sum
		sourceColumn: TotalSpend

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EstimatedRecovery
		dataType: double
		summarizeBy: sum
		sourceColumn: EstimatedRecovery

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ActionChannel
		dataType: string
		sourceColumn: ActionChannel

	column ActionType
		dataType: string
		sourceColumn: ActionType

	column Priority
		dataType: string
		sourceColumn: Priority

	column ScheduledDate
		dataType: string
		sourceColumn: ScheduledDate

	column Status
		dataType: string
		sourceColumn: Status

	column MessagePreview
		dataType: string
		sourceColumn: MessagePreview

	partition CampaignActions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\SNEVILLE\Tab2PBI\campaign_actions.csv"),[Delimiter=",",Encoding=1252,QuoteStyle=QuoteStyle.None]),
				    Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers,{{"CustomerKey",Int64.Type},{"ChurnRiskScore",type number},{"TotalSpend",type number},{"EstimatedRecovery",type number}},"en-US")
				in
				    Typed

