/// Calendar date dimension — used for time intelligence
table DimDate
	dataCategory: Time

	column DateKey
		dataType: int64
		isHidden
		sourceColumn: DateKey

	column Date
		dataType: dateTime
		isUnique
		sourceColumn: Date

	column Month
		dataType: string
		sourceColumn: Month

	column 'Month Number'
		dataType: int64
		isHidden
		sourceColumn: Month Number

	column Year
		dataType: int64
		sourceColumn: Year

	column Quarter
		dataType: int64
		sourceColumn: Quarter

	column 'Fiscal Year'
		dataType: int64
		sourceColumn: Fiscal Year

	column 'Fiscal Quarter'
		dataType: int64
		sourceColumn: Fiscal Quarter

	/// ISO week number of the year
	column 'Week Number' = WEEKNUM([Date])
		dataType: int64
		displayFolder: Date Details

	/// Full name of the day of the week
	column 'Day of Week' = FORMAT([Date], "dddd")
		dataType: string
		displayFolder: Date Details

	/// TRUE if the date falls on Saturday or Sunday
	column 'Is Weekend' = IF(WEEKDAY([Date], 2) >= 6, TRUE(), FALSE())
		dataType: boolean
		displayFolder: Date Details

	/// Month and year label formatted as e.g. Jan 2026
	column 'Month Year' = FORMAT([Date], "MMM YYYY")
		dataType: string
		displayFolder: Date Details

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Sql.Database("localhost\SQLEXPRESS", "AdventureWorksDW2022"),
				    tbl = Source{[Schema="dbo",Item="DimDate"]}[Data],
				    selected = Table.SelectColumns(tbl,{"DateKey","FullDateAlternateKey","EnglishMonthName","MonthNumberOfYear","CalendarYear","CalendarQuarter","FiscalYear","FiscalQuarter"}),
				    renamed = Table.RenameColumns(selected,{{"FullDateAlternateKey","Date"},{"EnglishMonthName","Month"},{"MonthNumberOfYear","Month Number"},{"CalendarYear","Year"},{"CalendarQuarter","Quarter"},{"FiscalYear","Fiscal Year"},{"FiscalQuarter","Fiscal Quarter"}}),
				    typed = Table.TransformColumnTypes(renamed,{{"DateKey",Int64.Type},{"Date",type datetime},{"Month Number",Int64.Type},{"Year",Int64.Type},{"Quarter",Int64.Type},{"Fiscal Year",Int64.Type},{"Fiscal Quarter",Int64.Type}},"en-US")
				in
				    typed

