/// Product dimension
table DimProduct

	column ProductKey
		dataType: int64
		isHidden
		sourceColumn: ProductKey

	column ProductSubcategoryKey
		dataType: int64
		isHidden
		sourceColumn: ProductSubcategoryKey

	column 'Product Name'
		dataType: string
		sourceColumn: Product Name

	column Color
		dataType: string
		sourceColumn: Color

	column StandardCost
		dataType: decimal
		sourceColumn: StandardCost

	column ListPrice
		dataType: decimal
		sourceColumn: ListPrice

	partition DimProduct = m
		mode: import
		source =
				let
				    Source = Sql.Database("localhost\SQLEXPRESS", "AdventureWorksDW2022"),
				    tbl = Source{[Schema="dbo",Item="DimProduct"]}[Data],
				    selected = Table.SelectColumns(tbl,{"ProductKey","ProductSubcategoryKey","EnglishProductName","Color","StandardCost","ListPrice"}),
				    renamed = Table.RenameColumns(selected,{{"EnglishProductName","Product Name"}}),
				    filtered = Table.SelectRows(renamed, each [ProductSubcategoryKey] <> null)
				in
				    filtered

