/// Internet (B2C) sales transactions — one row per product per order line
table FactInternetSales

	column CustomerKey
		dataType: int64
		isHidden
		sourceColumn: CustomerKey

	column ProductKey
		dataType: int64
		isHidden
		sourceColumn: ProductKey

	column OrderDateKey
		dataType: int64
		isHidden
		sourceColumn: OrderDateKey

	column SalesTerritoryKey
		dataType: int64
		isHidden
		sourceColumn: SalesTerritoryKey

	column PromotionKey
		dataType: int64
		isHidden
		sourceColumn: PromotionKey

	column OrderQuantity
		dataType: int64
		sourceColumn: OrderQuantity

	column UnitPrice
		dataType: double
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExtendedAmount
		dataType: double
		summarizeBy: sum
		sourceColumn: ExtendedAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalProductCost
		dataType: double
		summarizeBy: sum
		sourceColumn: TotalProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesAmount
		dataType: double
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountAmount
		dataType: double
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderDate
		dataType: dateTime
		sourceColumn: OrderDate

	partition FactInternetSales = m
		mode: import
		source =
				let
				    Source = Sql.Database("localhost\SQLEXPRESS", "AdventureWorksDW2022"),
				    tbl = Source{[Schema="dbo",Item="FactInternetSales"]}[Data],
				    selected = Table.SelectColumns(tbl,{"CustomerKey","ProductKey","OrderDateKey","SalesTerritoryKey","OrderQuantity","UnitPrice","ExtendedAmount","TotalProductCost","SalesAmount","DiscountAmount","OrderDate","PromotionKey"}),
				    typed = Table.TransformColumnTypes(selected,{{"CustomerKey",Int64.Type},{"ProductKey",Int64.Type},{"OrderDateKey",Int64.Type},{"SalesTerritoryKey",Int64.Type},{"OrderQuantity",Int64.Type},{"UnitPrice",type number},{"ExtendedAmount",type number},{"TotalProductCost",type number},{"SalesAmount",type number},{"DiscountAmount",type number},{"OrderDate",type datetime},{"PromotionKey",Int64.Type}},"en-US")
				in
				    typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

