/// ML churn risk scores and RFM metrics per customer
table ChurnScores

	column CustomerKey
		dataType: int64
		sourceColumn: CustomerKey

	column FirstName
		dataType: string
		sourceColumn: FirstName

	column LastName
		dataType: string
		sourceColumn: LastName

	column Occupation
		dataType: string
		sourceColumn: Occupation

	column Segment
		dataType: string
		sourceColumn: Segment

	column Recency
		dataType: int64
		sourceColumn: Recency

	column Frequency
		dataType: int64
		sourceColumn: Frequency

	column TotalSpend
		dataType: double
		summarizeBy: sum
		sourceColumn: TotalSpend

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AvgOrderValue
		dataType: double
		summarizeBy: sum
		sourceColumn: AvgOrderValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ChurnRiskScore
		dataType: double
		summarizeBy: sum
		sourceColumn: ChurnRiskScore

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RiskBand
		dataType: string
		sourceColumn: RiskBand

	column Churned
		dataType: int64
		sourceColumn: Churned

	partition ChurnScores = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\SNEVILLE\Tab2PBI\churn_scores.csv"),[Delimiter=",",Encoding=1252,QuoteStyle=QuoteStyle.None]),
				    Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers,{{"CustomerKey",Int64.Type},{"Segment",type text},{"Recency",Int64.Type},{"Frequency",Int64.Type},{"TotalSpend",type number},{"AvgOrderValue",type number},{"ChurnRiskScore",type number},{"RiskBand",type text},{"Churned",Int64.Type}},"en-US")
				in
				    Typed

