/// Sales quota targets per employee per quarter
table FactSalesQuota

	column SalesQuotaKey
		dataType: int64
		isHidden
		sourceColumn: SalesQuotaKey

	column EmployeeKey
		dataType: int64
		isHidden
		sourceColumn: EmployeeKey

	column QuotaDate
		dataType: dateTime
		sourceColumn: QuotaDate

	column SalesAmountQuota
		dataType: double
		summarizeBy: sum
		sourceColumn: SalesAmountQuota

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CalendarYear
		dataType: int64
		sourceColumn: CalendarYear

	column CalendarQuarter
		dataType: int64
		sourceColumn: CalendarQuarter

	partition FactSalesQuota = m
		mode: import
		source =
				let
				    Source = Sql.Database("localhost\SQLEXPRESS", "AdventureWorksDW2022"),
				    tbl = Source{[Schema="dbo",Item="FactSalesQuota"]}[Data],
				    selected = Table.SelectColumns(tbl,{"SalesQuotaKey","EmployeeKey","DateKey","SalesAmountQuota","CalendarYear","CalendarQuarter"}),
				    renamed = Table.RenameColumns(selected,{{"DateKey","QuotaDateKey"}}),
				    dated = Table.AddColumn(renamed,"QuotaDate",each #date([CalendarYear], ([CalendarQuarter]-1)*3+1, 1), type datetime),
				    typed = Table.TransformColumnTypes(dated,{{"SalesQuotaKey",Int64.Type},{"EmployeeKey",Int64.Type},{"SalesAmountQuota",type number},{"CalendarYear",Int64.Type},{"CalendarQuarter",Int64.Type}},"en-US"),
				    final = Table.RemoveColumns(typed,{"QuotaDateKey"})
				in
				    final

